services:
  - type: web
    name: houser-api
    runtime: python
    rootDir: ml-api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
    plan: free
